- hosts: all
  sudo: True
  vars_files:
    - "global_vars.yml"
  environment:
    LD_LIBRARY_PATH: /usr/local/lib
    USER: vagrant
  roles:
    - pre_config
    - liberasurecode
    - swift
    - post_config
