- hosts: all
  become: True
  vars_files:
    - "global_vars.yml"
  environment:
    LD_LIBRARY_PATH: /usr/local/lib
    USER: "{{ username }}"
  roles:
    - pre_config
    - liberasurecode
    - swift
    - post_config
