# demo_setup.yml
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    instance_name: foo
    ami_id: ami-d1315fb1
    aws_access_key: xxxx
    aws_secret_key: xxxx
    key_name: johnnywa 
    security_group: default 
    instance_type: t2.medium 
    wait: true
    assign_public_ip: yes
    vpc_subnet_id: subnet-93bf67f7
    region: us-west-1a
  tasks:
   - name: Provision a set of instances
     ec2:
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"
       key_name: "{{ key_name }}"
       group: "{{ security_group }}"
       instance_type: "{{ instance_type }}"
       image: "{{ ami_id }}"
       wait: "{{ wait }}"
       count: 1
       assign_public_ip: "{{ assign_public_ip }}"
       region: "{{ region }}"
       vpc_subnet_id: "{{ vpc_subnet_id }}"
       instance_tags:
           Name: "{{ instance_name }}"
     register: ec2

   - name: Add all instance public IPs to host group
     add_host: hostname={{ item.public_ip }} groups=ec2hosts
     with_items: ec2.instances
